services:
  orders-service:
    image: orders-service
    build:
      context: ./orders-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 193.233.193.42:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: order-group
    ports:
      - "8081:8081"


  payment-service:
    image: payment-service
    build:
      context: ./payment-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 193.233.193.42:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: payment-group
    ports:
      - "8082:8082"


  shipping-service:
    image: shipping-service
    build:
      context: ./shipping-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 193.233.193.42:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: shipping-group
    ports:
      - "8083:8083"

  notifications-service:
    image: notifications-service
    build:
      context: ./notifications-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 193.233.193.42:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: notification-group
    ports:
      - "8084:8084"
