spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/employees_db
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 10000