spring:
  kafka:
    topics:
      partitions: 10
      replication-factor: 1
    listener:
      concurrency: 10
      ack-mode: MANUAL
    bootstrap-servers: 193.233.193.42:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: '*'
      properties.spring.json.value.default.type: org.polina.practice.model.Order
server:
  port: 8084